version: 2.1

commands:
    install_and_test:
        parameters:
            composer_flags:
                type: string
                default: ""
            laravel:
                type: string
                default: ""
        steps:
            - checkout
            - run: echo 'export APP_ENV="test"' >> $BASH_ENV
            - run: composer self-update
            - run: composer require "laravel/framework=5.7" --prefer-source --no-interaction --no-suggest --no-autoloader
            - run: composer update << parameters.composer_flags >> --no-interaction --prefer-source --no-autoloader
            - run: vendor/bin/phpunit

workflows:
    version: 2
    build:
        jobs:
            - php72-laravel57
            - php72-laravel57-prefer-lowest

jobs:
    php72-laravel57-prefer-lowest:
        docker:
            - image: circleci/php:7.2
        steps:
            - install_and_test:
                  laravel: 5.7.*
                  composer_flags: --prefer-lowest
    php72-laravel57:
        docker:
            - image: circleci/php:7.2
        steps:
            - install_and_test:
                  laravel: 5.7.*