# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  test:
    docker:
      - image: circleci/php:7.1.23-cli-stretch

    working_directory: ~/repo

    steps:
      - run:
          name: Install bcmath and gmp extensions
          command: |
            sudo apt-get install -y libgmp-dev libxml2-dev
            sudo docker-php-ext-configure bcmath
            sudo docker-php-ext-configure gmp
            sudo docker-php-ext-configure soap
            sudo docker-php-ext-install bcmath gmp soap

      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - br-dependencies-{{ checksum "app/composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - br-dependencies-

      - run:
          name: Install dependencies
          command: |
            cd ~/repo/app
            composer install -n --prefer-dist --no-scripts

      - save_cache:
          paths:
            - ~/repo/app/vendor
          key: br-dependencies-{{ checksum "app/composer.json" }}

      # run tests!
      - run:
          name: Run tests
          command: |
            cd ~/repo/app
            cp .env.testing .env
            ../../../vendor/bin/phpunit

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - test
      - build_image:
          requires:
            - test
          filters:
            branches:
              only:
                - develop
                - master
      - push_image:
          requires:
            - test
            - build_image
          filters:
            branches:
              only:
                - develop
                - master
      - deploy_dev:
          requires:
            - test
            - build_image
            - push_image
          filters:
            branches:
              only:
                - develop
